---
- host: dev
  connection: ssh 
  become: yes
  environment:
   https_proxy: "http://10.133.12.181:80"
   http_proxy: "http://10.133.12.181:80"
   
  tasks:
   - name: remove the excisting docker packages in server.
     apt:
      name:
        - docker
        - docker.io
        - docker-engine
        - containerd
      state: absent
        purge: yes
      ignore_errors: yes
	  
  - name: Install dependencies
     apt:
       name:
        - ca-certificates
        - curl
        - gnupg
       state: present
        update_cache: yes
		
   - name: Create Docker keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
   - name: Add Docker’s official GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
   - name: Set up Docker repository
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$LATEST_VERSION}") stable" > /etc/apt/sources.list.d/docker.list
      args:
        executable: /bin/bash
		
   - name: Update apt package index
      apt:
        update_cache: yes
   - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes
      notify:
        - Restart Docker service

  handlers:
   - name: Restart Docker service
      service:
        name: docker
        state: restarted
